# Generated by Django 2.1 on 2018-08-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('static_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
